
name: Node.js CI

on:
  push:
    branches: [ "user1" ]
  pull_request:
    branches: [ "user1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Build Docker Image
      run: docker build -t albin05/demo:1.0 test1\src
    - name: Docker login
      run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: docker push albin05/demo:1.0
    